const process = {
  title: 'npm',
  version: 'v10.15.3',
  versions: { 
    http_parser: '2.8.0',
    node: '10.15.3',
    v8: '6.8.275.32-node.51',
    uv: '1.23.2',
    zlib: '1.2.11',
    ares: '1.15.0',
    modules: '64',
    nghttp2: '1.34.0',
    napi: '3',
    openssl: '1.1.0j',
    icu: '62.1',
    unicode: '11.0',
    cldr: '33.1',
    tz: '2018e' 
  },
  arch: 'x64',
  platform: 'win32',
  release: { 
    name: 'node',
    lts: 'Dubnium',
    sourceUrl: 'https://nodejs.org/download/release/v10.15.3/node-v10.15.3.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz',
    libUrl: 'https://nodejs.org/download/release/v10.15.3/win-x64/node.lib' 
  },
  argv: [ 
    'C:\\Program Files\\nodejs\\node.exe',
    'C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\binpage\\scripts\\start.js' 
  ],
  execArgv: [],
  env: { 
    ALLUSERSPROFILE: 'C:\\ProgramData',
    ANDROID_HOME: 'C:\\Users\\noten\\AppData\\Local\\Android\\Sdk',
    APPDATA: 'C:\\Users\\noten\\AppData\\Roaming',
    ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
    ChocolateyLastPathUpdate: '131986651044797040',
    CLASSPATH: 'C:\\Program Files\\Java\\jdk1.8.0_201\\bin',
    COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files', 'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'LAPTOP-ROJ73HAH',
    COMSPEC: 'C:\\WINDOWS\\system32\\cmd.exe',
    configsetroot: 'C:\\WINDOWS\\ConfigSetRoot',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    EXEPATH: 'C:\\Program Files\\Git\\bin',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    HOME: 'C:\\Users\\noten',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\noten',
    INIT_CWD: 'C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\binpage',
    INTEL_DEV_REDIST: 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\',
    JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.8.0_201',
    LANG: 'ko_KR.UTF-8',
    LOCALAPPDATA: 'C:\\Users\\noten\\AppData\\Local',
    LOGONSERVER: '\\\\LAPTOP-ROJ73HAH',
    MIC_LD_LIBRARY_PATH: 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic',
    MSYSTEM: 'MINGW64',
    NODE: 'C:\\Program Files\\nodejs\\node.exe',
    NODE_PATH: 'src',
    npm_config_access: '',
    npm_config_allow_same_version: '',
    npm_config_also: '',
    npm_config_always_auth: '',
    npm_config_argv: '{"remain":[],"cooked":["run","start_react"],"original":["run","start_react"]}',
    npm_config_audit: 'true',
    npm_config_audit_level: 'low',
    npm_config_auth_type: 'legacy',
    npm_config_bin_links: 'true',
    npm_config_browser: '',
    npm_config_ca: '',
    npm_config_cache: 'C:\\Users\\noten\\AppData\\Roaming\\npm-cache',
    npm_config_cache_lock_retries: '10',
    npm_config_cache_lock_stale: '60000',
    npm_config_cache_lock_wait: '10000',
    npm_config_cache_max: 'Infinity',
    npm_config_cache_min: '10',
    npm_config_cafile: '',
    npm_config_cert: '',
    npm_config_cidr: '',
    npm_config_color: 'true',
    npm_config_commit_hooks: 'true',
    npm_config_depth: 'Infinity',
    npm_config_description: 'true',
    npm_config_dev: '',
    npm_config_dry_run: '',
    npm_config_editor: 'notepad.exe',
    npm_config_engine_strict: '',
    npm_config_fetch_retries: '2',
    npm_config_fetch_retry_factor: '10',
    npm_config_fetch_retry_maxtimeout: '60000',
    npm_config_fetch_retry_mintimeout: '10000',
    npm_config_force: '',
    npm_config_git: 'git',
    npm_config_git_tag_version: 'true',
    npm_config_global: '',
    npm_config_globalconfig: 'C:\\Users\\noten\\AppData\\Roaming\\npm\\etc\\npmrc',
    npm_config_globalignorefile: 'C:\\Users\\noten\\AppData\\Roaming\\npm\\etc\\npmignore',
    npm_config_global_style: '',
    npm_config_group: '',
    npm_config_ham_it_up: '',
    npm_config_heading: 'npm',
    npm_config_https_proxy: '',
    npm_config_if_present: '',
    npm_config_ignore_prepublish: '',
    npm_config_ignore_scripts: '',
    npm_config_init_author_email: '',
    npm_config_init_author_name: '',
    npm_config_init_author_url: '',
    npm_config_init_license: 'ISC',
    npm_config_init_module: 'C:\\Users\\noten\\.npm-init.js',
    npm_config_init_version: '1.0.0',
    npm_config_json: '',
    npm_config_key: '',
    npm_config_legacy_bundling: '',
    npm_config_link: '',
    npm_config_local_address: '',
    npm_config_loglevel: 'notice',
    npm_config_logs_max: '10',
    npm_config_long: '',
    npm_config_maxsockets: '50',
    npm_config_message: '%s',
    npm_config_metrics_registry: 'https://registry.npmjs.org/',
    npm_config_node_gyp: 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
    npm_config_node_options: '',
    npm_config_node_version: '10.15.3',
    npm_config_noproxy: '',
    npm_config_offline: '',
    npm_config_onload_script: '',
    npm_config_only: '',
    npm_config_optional: 'true',
    npm_config_otp: '',
    npm_config_package_lock: 'true',
    npm_config_package_lock_only: '',
    npm_config_parseable: '',
    npm_config_prefer_offline: '',
    npm_config_prefer_online: '',
    npm_config_prefix: 'C:\\Users\\noten\\AppData\\Roaming\\npm',
    npm_config_preid: '',
    npm_config_production: '',
    npm_config_progress: 'true',
    npm_config_proxy: '',
    npm_config_read_only: '',
    npm_config_rebuild_bundle: 'true',
    npm_config_registry: 'https://registry.npmjs.org/',
    npm_config_rollback: 'true',
    npm_config_save: 'true',
    npm_config_save_bundle: '',
    npm_config_save_dev: '',
    npm_config_save_exact: '',
    npm_config_save_optional: '',
    npm_config_save_prefix: '^',
    npm_config_save_prod: '',
    npm_config_scope: '',
    npm_config_scripts_prepend_node_path: 'warn-only',
    npm_config_script_shell: '',
    npm_config_searchexclude: '',
    npm_config_searchlimit: '20',
    npm_config_searchopts: '',
    npm_config_searchstaleness: '900',
    npm_config_send_metrics: '',
    npm_config_shell: 'C:\\WINDOWS\\system32\\cmd.exe',
    npm_config_shrinkwrap: 'true',
    npm_config_sign_git_commit: '',
    npm_config_sign_git_tag: '',
    npm_config_sso_poll_frequency: '500',
    npm_config_sso_type: 'oauth',
    npm_config_strict_ssl: 'true',
    npm_config_tag: 'latest',
    npm_config_tag_version_prefix: 'v',
    npm_config_timing: '',
    npm_config_tmp: 'C:\\Users\\noten\\AppData\\Local\\Temp',
    npm_config_umask: '0000',
    npm_config_unicode: '',
    npm_config_unsafe_perm: 'true',
    npm_config_update_notifier: 'true',
    npm_config_usage: '',
    npm_config_user: '',
    npm_config_userconfig: 'C:\\Users\\noten\\.npmrc',
    npm_config_user_agent: 'npm/6.4.1 node/v10.15.3 win32 x64',
    npm_config_version: '',
    npm_config_versions: '',
    npm_config_viewer: 'browser',
    npm_execpath: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    npm_lifecycle_event: 'start_react',
    npm_lifecycle_script: 'cross-env NODE_PATH=src node scripts/start.js',
    npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
    npm_package_babel_presets_0: 'react-app',
    npm_package_browserslist_0: '>0.2%',
    npm_package_browserslist_1: 'not dead',
    npm_package_browserslist_2: 'not ie <= 11',
    npm_package_browserslist_3: 'not op_mini all',
    npm_package_dependencies_autoprefixer: '^9.5.1',
    npm_package_dependencies_babel_loader: '^8.0.5',
    npm_package_dependencies_babel_preset_es2015: '^6.24.1',
    npm_package_dependencies_babel_preset_react: '^6.24.1',
    npm_package_dependencies_babel_runtime: '^6.26.0',
    npm_package_dependencies_case_sensitive_paths_webpack_plugin: '2.1.1',
    npm_package_dependencies_chalk: '1.1.3',
    npm_package_dependencies_classnames: '^2.2.5',
    npm_package_dependencies_cross_env: '^5.2.0',
    npm_package_dependencies_css_loader: '0.28.7',
    npm_package_dependencies_dotenv: '4.0.0',
    npm_package_dependencies_dotenv_expand: '4.2.0',
    npm_package_dependencies_eslint: '^5.15.1',
    npm_package_dependencies_eslint_config_babel: '^9.0.0',
    npm_package_dependencies_eslint_plugin_flowtype: '^3.2.1',
    npm_package_dependencies_eslint_plugin_import: '^2.16.0',
    npm_package_dependencies_eslint_plugin_prettier: '^3.0.1',
    npm_package_dependencies_extract_text_webpack_plugin: '3.0.2',
    npm_package_dependencies_file_loader: '1.1.5',
    npm_package_dependencies_firebase: '^5.9.2',
    npm_package_dependencies_fs_extra: '3.0.1',
    npm_package_dependencies_html_webpack_plugin: '2.29.0',
    npm_package_dependencies_next: '^8.0.4',
    npm_package_dependencies_node_sass: '^4.9.0',
    npm_package_dependencies_object_assign: '4.1.1',
    npm_package_dependencies_postcss_flexbugs_fixes: '3.2.0',
    npm_package_dependencies_postcss_loader: '2.0.8',
    npm_package_dependencies_promise: '8.0.1',
    npm_package_dependencies_prop_types: '^15.7.2',
    npm_package_dependencies_raf: '3.4.0',
    npm_package_dependencies_react: '^16.8.6',
    npm_package_dependencies_react_dev_utils: '^5.0.1',
    npm_package_dependencies_react_dom: '^16.8.6',
    npm_package_dependencies_react_router_dom: '^4.3.1',
    npm_package_dependencies_react_scripts: '2.1.8',
    npm_package_dependencies_resolve: '1.6.0',
    npm_package_dependencies_sass_loader: '^7.0.1',
    npm_package_dependencies_style_loader: '0.19.0',
    npm_package_dependencies_sw_precache_webpack_plugin: '0.11.4',
    npm_package_dependencies_url_loader: '0.6.2',
    npm_package_dependencies_webpack: '^3.8.1',
    npm_package_dependencies_webpack_manifest_plugin: '1.3.2',
    npm_package_dependencies_whatwg_fetch: '2.0.3',
    npm_package_description: 'This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).',
    npm_package_devDependencies_webpack_dev_server: '^2.9.4',
    npm_package_eslintConfig_extends: 'react-app',
    npm_package_gitHead: 'f52158a6ff3853521cd85e781399fb5b3b252959',
    npm_package_name: 'binpage',
    npm_package_private: 'true',
    npm_package_readmeFilename: 'README.md',
    npm_package_scripts_build: 'next build',
    npm_package_scripts_build_react: 'cross-env NODE_PATH=src node scripts/build.js',
    npm_package_scripts_dev: 'next -p 9090',
    npm_package_scripts_nodejs: 'nodemon --exec babel-node nodejs/index.js',
    npm_package_scripts_start: 'next start',
    npm_package_scripts_start_react: 'cross-env NODE_PATH=src node scripts/start.js',
    npm_package_scripts_test_react: 'node scripts/test.js --env=jsdom',
    npm_package_version: '0.1.0',
    NUMBER_OF_PROCESSORS: '8',
    OneDrive: 'C:\\Users\\noten\\OneDrive',
    OneDriveConsumer: 'C:\\Users\\noten\\OneDrive',
    OS: 'Windows_NT',
    PATH:
    'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\binpage\\node_modules\\.bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\noten\\bin;C:\\Python27;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Java\\jdk1.8.0_201\\bin;C:\\Program Files (x86)\\Yarn\\bin;C:\\Users\\noten\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\noten\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\noten\\AppData\\Roaming\\npm;C:\\Users\\noten\\AppData\\Local\\Yarn\\bin',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC',
    PLINK_PROTOCOL: 'ssh',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '9e0a',
    ProgramData: 'C:\\ProgramData',
    PROGRAMFILES: 'C:\\Program Files', 'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PROMPT: '$P$G',
    PSModulePath: '%ProgramFiles%\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    PWD: 'C:/Users/noten/OneDrive/바탕 화면/github/binpage',
    SHLVL: '2',
    SYSTEMDRIVE: 'C:',
    SYSTEMROOT: 'C:\\WINDOWS',
    TEMP: 'C:\\Users\\noten\\AppData\\Local\\Temp',
    TERM: 'cygwin',
    TERM_PROGRAM: 'vscode',
    TERM_PROGRAM_VERSION: '1.33.0',
    TMP: 'C:\\Users\\noten\\AppData\\Local\\Temp',
    USERDOMAIN: 'LAPTOP-ROJ73HAH',
    USERDOMAIN_ROAMINGPROFILE: 'LAPTOP-ROJ73HAH',
    USERNAME: 'noten',
    USERPROFILE: 'C:\\Users\\noten',
    WINDIR: 'C:\\WINDOWS',
    _: 'C:/Program Files/nodejs/node.exe' 
  },
  pid: 28600,
  features: { 
    debug: false,
    uv: true,
    ipv6: true,
    tls_alpn: true,
    tls_sni: true,
    tls_ocsp: true,
    tls: true 
  },
  ppid: 28128,
  execPath: 'C:\\Program Files\\nodejs\\node.exe',
  debugPort: 9229,
  _debugProcess: [],
  _debugEnd: [],
  _startProfilerIdleNotifier: [],
  _stopProfilerIdleNotifier: [],
  abort: [],
  chdir: [],
  umask: [],
  _getActiveRequests: [],
  _getActiveHandles: [],
  _kill: [],
  cwd: [],
  dlopen: [],
  reallyExit: [],
  uptime: [],
  _rawDebug: [],
  moduleLoadList:[ 
    'Internal Binding module_wrap',
    'Binding contextify',
    'Internal Binding worker',
    'NativeModule events',
    'NativeModule internal/async_hooks',
    'NativeModule internal/errors',
    'Binding uv',
    'Binding buffer',
    'Binding async_wrap',
    'Internal Binding async_wrap',
    'Binding config',
    'Binding icu',
    'NativeModule util',
    'NativeModule internal/util/inspect',
    'Binding util',
    'NativeModule internal/util',
    'Binding constants',
    'Internal Binding types',
    'NativeModule internal/util/types',
    'NativeModule internal/validators',
    'NativeModule internal/encoding',
    'Internal Binding icu',
    'NativeModule buffer',
    'NativeModule internal/buffer',
    'NativeModule internal/process/per_thread',
    'NativeModule internal/process/main_thread_only',
    'NativeModule internal/process/stdio',
    'NativeModule assert',
    'NativeModule internal/assert',
    'NativeModule fs',
    'NativeModule path',
    'NativeModule internal/constants',
    'Binding fs',
    'NativeModule internal/fs/streams',
    'NativeModule internal/fs/utils',
    'NativeModule stream',
    'NativeModule internal/streams/pipeline',
    'NativeModule internal/streams/end-of-stream',
    'NativeModule internal/streams/legacy',
    'NativeModule _stream_readable',
    'NativeModule internal/streams/buffer_list',
    'NativeModule internal/streams/destroy',
    'NativeModule internal/streams/state',
    'NativeModule _stream_writable',
    'NativeModule _stream_duplex',
    'NativeModule _stream_transform',
    'NativeModule _stream_passthrough',
    'NativeModule internal/url',
    'NativeModule internal/querystring',
    'Binding url',
    'NativeModule internal/process/warning',
    'NativeModule internal/process/next_tick',
    'NativeModule internal/process/promises',
    'Internal Binding util',
    'NativeModule internal/fixed_queue',
    'Binding performance',
    'Binding trace_events',
    'NativeModule internal/inspector_async_hook',
    'Binding inspector',
    'NativeModule internal/options',
    'Internal Binding options',
    'NativeModule timers',
    'Binding timer_wrap',
    'NativeModule internal/linkedlist',
    'NativeModule internal/timers',
    'NativeModule console',
    'Binding tty_wrap',
    'Internal Binding tty_wrap',
    'NativeModule tty',
    'NativeModule net',
    'NativeModule internal/net',
    'Binding stream_wrap',
    'Binding tcp_wrap',
    'Binding pipe_wrap',
    'NativeModule internal/stream_base_commons',
    'Internal Binding stream_wrap',
    'Internal Binding uv',
    'NativeModule internal/tty',
    'Binding signal_wrap',
    'NativeModule internal/modules/cjs/loader',
    'NativeModule vm',
    'NativeModule url',
    'NativeModule internal/safe_globals',
    'NativeModule internal/modules/cjs/helpers',
    'NativeModule os',
    'Binding os' 
  ],
  binding: [],
  _linkedBinding: [],
  _events: {
    newListener: [],
    removeListener: [],
    warning: [],
    SIGWINCH: [ [], [] ] 
  },
  _eventsCount: 4,
  _maxListeners: undefined,
  _fatalException: [],
  domain: null,
  _exiting: false,
  assert: [],
  config: { 
    target_defaults:{ 
      cflags: [],
      default_configuration: 'Release',
      defines: [],
      include_dirs: [],
      libraries: [] 
    },
    variables: { 
      asan: 0,
      build_v8_with_gn: false,
      coverage: false,
      debug_nghttp2: false,
      enable_lto: false,
      enable_pgo_generate: false,
      enable_pgo_use: false,
      force_dynamic_crt: 0,
      host_arch: 'x64',
      icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt62l.dat',
      icu_endianness: 'l',
      icu_gyp_path: 'tools/icu/icu-generic.gyp',
      icu_locales: 'en,root',
      icu_path: 'deps/icu-small',
      icu_small: true,
      icu_ver_major: '62',
      nasm_version: '2.14',
      node_byteorder: 'little',
      node_debug_lib: false,
      node_enable_d8: false,
      node_enable_v8_vtunejit: false,
      node_install_npm: true,
      node_module_version: 64,
      node_no_browser_globals: false,
      node_prefix: '/usr/local',
      node_release_urlbase: 'https://nodejs.org/download/release/',
      node_shared: false,
      node_shared_cares: false,
      node_shared_http_parser: false,
      node_shared_libuv: false,
      node_shared_nghttp2: false,
      node_shared_openssl: false,
      node_shared_zlib: false,
      node_tag: '',
      node_target_type: 'executable',
      node_use_bundled_v8: true,
      node_use_dtrace: false,
      node_use_etw: true,
      node_use_large_pages: false,
      node_use_openssl: true,
      node_use_pch: false,
      node_use_perfctr: true,
      node_use_v8_platform: true,
      node_with_ltcg: true,
      node_without_node_options: false,
      openssl_fips: '',
      openssl_no_asm: 0,
      shlib_suffix: 'so.64',
      target_arch: 'x64',
      v8_enable_gdbjit: 0,
      v8_enable_i18n_support: 1,
      v8_enable_inspector: 1,
      v8_no_strict_aliasing: 1,
      v8_optimized_debug: 0,
      v8_promise_internal_field_count: 1,
      v8_random_seed: 0,
      v8_trace_maps: 0,
      v8_typed_array_max_size_in_heap: 0,
      v8_use_snapshot: true,
      want_separate_host_toolset: 0 
    } 
  },
  setUncaughtExceptionCaptureCallback: [],
  hasUncaughtExceptionCaptureCallback: [],
  emitWarning: [],
  nextTick: [],
  _tickCallback: [],
  stdout: [],
  stderr: [],
  stdin: [],
  openStdin: [],
  hrtime: {},
  cpuUsage: [],
  memoryUsage: [],
  exit: [],
  kill: [],
  argv0: 'node',
  allowedNodeEnvironmentFlags: [],
  mainModule: {
    id: '.',
    exports: {},
    parent: null,
    filename: 'C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\binpage\\scripts\\start.js',
    loaded: false,
    children: [],
    paths:[ 
      'C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\binpage\\scripts\\node_modules',
      'C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\binpage\\node_modules',
      'C:\\Users\\noten\\OneDrive\\바탕 화면\\github\\node_modules',
      'C:\\Users\\noten\\OneDrive\\바탕 화면\\node_modules',
      'C:\\Users\\noten\\OneDrive\\node_modules',
      'C:\\Users\\noten\\node_modules',
      'C:\\Users\\node_modules',
      'C:\\node_modules' 
    ] 
  } 
}